<?php
/**
 * Created by PhpStorm.
 * User: helgdd
 * Date: 11.07.2016
 * Time: 9:00
 */
namespace app\components\grid;

use yii\helpers\Html;


class GridView extends  \yii\grid\GridView
{
    public $tableOptions = ['class' => 'table striped bordered'];
    public $idTBody = 'sortabletbl';
    
    public function renderTableRow($model, $key, $index)
    {
        $cells = [];
        /* @var $column Column */
        foreach ($this->columns as $column) {
            $cells[] = $column->renderDataCell($model, $key, $index);
        }
        if ($this->rowOptions instanceof Closure) {
            $options = call_user_func($this->rowOptions, $model, $key, $index, $this);
        } else {
            $options = $this->rowOptions;
        }
        $options['data-key'] = is_array($key) ? json_encode($key) : (string) $key;

        $options['idsort'] =  is_array($key) ? json_encode($key) : 'sort_'. (string) $key;

        return Html::tag('tr', implode('', $cells), $options);
        
       // return parent::renderTableRow($model, $key, $index); // TODO: Change the autogenerated stub
    }

    public function renderTableBody()
    {
        $models = array_values($this->dataProvider->getModels());
        $keys = $this->dataProvider->getKeys();
        $rows = [];
        foreach ($models as $index => $model) {
            $key = $keys[$index];
            if ($this->beforeRow !== null) {
                $row = call_user_func($this->beforeRow, $model, $key, $index, $this);
                if (!empty($row)) {
                    $rows[] = $row;
                }
            }

            $rows[] = $this->renderTableRow($model, $key, $index);

            if ($this->afterRow !== null) {
                $row = call_user_func($this->afterRow, $model, $key, $index, $this);
                if (!empty($row)) {
                    $rows[] = $row;
                }
            }
        }

//  'tableOptions'=> [ 'id'=>'sortabletbl'],
        if (empty($rows)) {
            $colspan = count($this->columns);

            return "<tbody id='".$this->idTBody."'>\n<tr><td colspan=\"$colspan\">" . $this->renderEmpty() . "</td></tr>\n</tbody>";
        } else {
            return "<tbody id='".$this->idTBody."'>\n" . implode("\n", $rows) . "\n</tbody>";
        }
    }



}