<?php

namespace app\modules\news\assets;

use yii\web\AssetBundle;

/**
 * Main frontend application asset bundle.
 */
class AssetCatalogEnd extends AssetBundle
{
    public $basePath = '@webroot/themes/news';
    public $baseUrl = '@web/themes/news';
    public $css = [
        'fancy/jquery.fancybox.min.css',
    ];
    public $js = [

        'fancy/jquery.fancybox.min.js',
        'scripts/general.js',
        'scripts/category.js',

        'scripts/jquery.maskedinput.min.js'

    ];
    public $jsOptions = ['position' => \yii\web\View::POS_END];

    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }

}
